# Generated by Django 3.0.3 on 2020-02-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200227_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassi',
            name='numero',
            field=models.CharField(help_text='Máximo 16 caracteres', max_length=16, unique=True, verbose_name='Chassi'),
        ),
    ]
